drop table  IF EXISTS users CASCADE;
drop table  IF EXISTS user_roles CASCADE;
drop table  IF EXISTS roles CASCADE;
drop table  IF EXISTS task CASCADE;
drop table  IF EXISTS subtasks CASCADE;
drop table  IF EXISTS status CASCADE;
drop table  IF EXISTS task_types CASCADE;

create TABLE users(
        user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name varchar(40) NOT NULL,
        user_login varchar(40) NOT NULL,
        password varchar(40) NOT NULL,
        CONSTRAINT login_const UNIQUE(user_login)
);

create TABLE roles(
        role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role varchar(40),
        CONSTRAINT rolt_const UNIQUE(role)
);

create TABLE user_roles(
		user_roles_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_login varchar(40) NOT NULL REFERENCES users (user_login),
        user_role varchar(40) NOT NULL REFERENCES roles (role_id)
);

create TABLE status(
        status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
        status_name varchar(40) NOT NULL,
        CONSTRAINT status_const UNIQUE(status_name)
);

create TABLE task_types(
        task_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_type_name varchar(60) NOT NULL,
        CONSTRAINT task_types_const UNIQUE(task_type_name)
);

create TABLE task(
        task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_name varchar(60) NOT NULL,
        task_status_id INTEGER NOT NULL REFERENCES status (status_id),
        task_description varchar(2000) NOT NULL,
        parent_task_id INTEGER,
        user_login varchar(40) NOT NULL REFERENCES users (user_login),
        create_time timestamp NOT NULL,
        update_time timestamp,
        task_type_id INTEGER REFERENCES task_types (task_type_id)
);


-- По умолчанию любая задача имеет task_status_id = 1, что соответствует статусу NEW
alter table task
alter task_status_id SET DEFAULT 1;

-- По умолчанию у задачи имеет parent_task_id = 0, что означает отсутствие родителя, т.о. задача без родителя
-- является проектом
alter table task
alter parent_task_id SET DEFAULT 0;

alter table task
alter create_time SET DEFAULT now();

alter table task
alter update_time SET DEFAULT now();

